export const roles = [
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Data Engineer",
  "Data Analyst",
  "DevOps Engineer",
  "Full-Stack Developer",
  "IT Enthusiast",
  "Tech Lead",
];

export const techStack = {
  frontend: [
    { name: "React", icon: "" },
    { name: "Next.js", icon: "" },
    { name: "Vue.js", icon: "" },
    { name: "Astro", icon: "" },
    { name: "TypeScript", icon: "" },
    { name: "JavaScript", icon: "" },
    { name: "HTML5", icon: "" },
    { name: "CSS3", icon: "" },
    { name: "Tailwind CSS", icon: "" },
    { name: "Bootstrap", icon: "" },
    { name: "shadcn/ui", icon: "" },
    { name: "Chakra UI", icon: "" },
    { name: "Material UI", icon: "" },
    { name: "SCSS/SASS", icon: "" },
    { name: "Redux", icon: "" },
    { name: "Zustand", icon: "" },
    { name: "React Query", icon: "" },
    { name: "Framer Motion", icon: "" },
    { name: "Electron", icon: "" },
    { name: "Flutter", icon: "" },
    { name: "Jest", icon: "" },
    { name: "Cypress", icon: "" },
    { name: "Playwright", icon: "" },
    { name: "Storybook", icon: "" },
  ],
  backend: [
    { name: "Java", icon: "" },
    { name: "Spring Boot", icon: "" },
    { name: "Go", icon: "" },
    { name: "Node.js", icon: "" },
    { name: "Express.js", icon: "" },
    { name: "NestJS", icon: "" },
    { name: "Fastify", icon: "" },
    { name: "Python", icon: "" },
    { name: "FastAPI", icon: "" },
    { name: "Django", icon: "" },
    { name: "Flask", icon: "" },
    { name: "PHP", icon: "" },
    { name: "Laravel", icon: "" },
    { name: "CodeIgniter 4", icon: "" },
    { name: "REST API", icon: "" },
    { name: "GraphQL", icon: "" },
    { name: "gRPC", icon: "" },
    { name: "Protocol Buffers", icon: "" },
    { name: "WebSocket", icon: "" },
    { name: "JWT", icon: "" },
    { name: "OAuth", icon: "" },
    { name: "Clerk", icon: "" },
    { name: "Prisma", icon: "" },
    { name: "Go Fiber", icon: "" },
    { name: "Strapi", icon: "" },
    { name: "WordPress", icon: "" },
  ],
  database: [
    { name: "PostgreSQL", icon: "" },
    { name: "MySQL", icon: "" },
    { name: "MongoDB", icon: "" },
    { name: "Redis", icon: "" },
    { name: "Elasticsearch", icon: "" },
    { name: "TimescaleDB", icon: "" },
    { name: "ClickHouse", icon: "" },
    { name: "Supabase", icon: "" },
    { name: "Firebase", icon: "" },
    { name: "Convex", icon: "" },
    { name: "PlanetScale", icon: "" },
    { name: "SQLite", icon: "" },
    { name: "DynamoDB", icon: "" },
  ],
  devops: [
    { name: "Docker", icon: "" },
    { name: "Kubernetes", icon: "" },
    { name: "CI/CD", icon: "" },
    { name: "GitHub Actions", icon: "" },
    { name: "Jenkins", icon: "" },
    { name: "AWS", icon: "" },
    { name: "GCP", icon: "" },
    { name: "Nginx", icon: "" },
    { name: "Linux", icon: "" },
    { name: "Terraform", icon: "" },
  ],
  data: [
    { name: "Apache Kafka", icon: "" },
    { name: "Apache Spark", icon: "" },
    { name: "PySpark", icon: "" },
    { name: "Airflow", icon: "" },
    { name: "dbt", icon: "" },
    { name: "Debezium", icon: "" },
    { name: "Delta Lake", icon: "" },
    { name: "MinIO", icon: "" },
    { name: "Trino", icon: "" },
    { name: "MLflow", icon: "" },
    { name: "Great Expectations", icon: "" },
    { name: "Streamlit", icon: "" },
    { name: "Pandas", icon: "" },
    { name: "NumPy", icon: "" },
    { name: "R", icon: "" },
    { name: "TensorFlow", icon: "" },
    { name: "Scikit-learn", icon: "" },
    { name: "OpenCV", icon: "" },
    { name: "Power BI", icon: "" },
    { name: "Tableau", icon: "" },
    { name: "Jupyter", icon: "" },
  ],
  tools: [
    { name: "VS Code", icon: "" },
    { name: "Git", icon: "" },
    { name: "GitHub", icon: "" },
    { name: "Postman", icon: "" },
    { name: "Figma", icon: "" },
    { name: "APIDog", icon: "" },
    { name: "DBeaver", icon: "" },
    { name: "TablePlus", icon: "" },
    { name: "Insomnia", icon: "" },
    { name: "XAMPP", icon: "" },
    { name: "LaTeX", icon: "" },
    { name: "Jira", icon: "" },
    { name: "Notion", icon: "" },
    { name: "Slack", icon: "" },
  ],
  monitoring: [
    { name: "Grafana", icon: "" },
    { name: "Prometheus", icon: "" },
    { name: "Jaeger", icon: "" },
    { name: "Zipkin", icon: "" },
    { name: "OpenTelemetry", icon: "" },
    { name: "Datadog", icon: "" },
    { name: "Sentry", icon: "" },
    { name: "ELK Stack", icon: "" },
    { name: "New Relic", icon: "" },
  ],
};

export interface Project {
  id: number;
  title: string;
  description: string;
  longDescription?: string;
  highlights?: string[];
  principles?: string[];
  tech: string[];
  github: string;
  deployment: string | null;
  images: string[];
  featured: boolean;
}

export const projects: Project[] = [
  {
    id: 14,
    title: "SmartGig Platform",
    description:
      "Production-grade Freelance Intelligence Marketplace — 7 independent Java Spring Boot microservices with graph-based skill matching, AI price prediction, and end-to-end distributed tracing.",
    longDescription:
      "A production-grade Freelance Intelligence Marketplace built with Java Spring Boot 3.x Microservices Architecture. 7 fully independent microservices — API Gateway, Auth, User, Project, Intelligence, Notification, and Analytics — each with its own database, independently deployable and scalable. Features a Graph-based Skill Matching Engine using Jaccard Similarity and weighted graph traversal, an AI-powered Price Prediction Engine with custom rule-based scoring (no external ML library), full-text search with Elasticsearch 8, and real-time WebSocket notifications driven by Kafka events. Nightly trend analytics run via Quartz batch jobs and every request is traced end-to-end with Zipkin. 60%+ test coverage via Testcontainers + JUnit 5 + RestAssured E2E tests.",
    highlights: [
      "Graph-based Skill Matching Engine: Jaccard Similarity + weighted graph traversal for intelligent freelancer-project pairing",
      "AI-powered Price Prediction Engine + Skill Gap Analysis via directed weighted skill relationship graphs (no external ML library)",
      "Real-time WebSocket (STOMP) notifications driven by Kafka events with Dead Letter Topic handling and Manual ACK + Idempotency",
      "E2E distributed tracing with Zipkin, Testcontainers integration tests, Awaitility for async assertions, 60%+ Jacoco coverage",
    ],
    principles: [
      "Database-per-Service",
      "Event-Driven (Choreography Saga)",
      "CQRS Lite",
      "Outbox Pattern",
      "Circuit Breaker (Resilience4j)",
      "Dead Letter Topics",
      "API Gateway Pattern",
      "Manual Kafka ACK + Idempotency",
      "Multi-stage Docker Builds",
    ],
    tech: ["Java 21", "Spring Boot 3.2", "Spring Cloud Gateway", "Spring Security", "JWT", "Apache Kafka", "Elasticsearch", "PostgreSQL", "MongoDB", "Redis", "Netflix Eureka", "OpenFeign", "Resilience4j", "Spring State Machine", "Quartz Scheduler", "Prometheus", "Grafana", "Zipkin", "Docker", "GitHub Actions"],
    github: "https://github.com/albertnanda19/SmartGig-Platform",
    deployment: null,
    images: [
      "/images/projects/smartgig-platform/Gateway Root.png",
      "/images/projects/smartgig-platform/Prometheus.png",
      "/images/projects/smartgig-platform/Grafana.png",
      "/images/projects/smartgig-platform/Zipkin.png",
      "/images/projects/smartgig-platform/Eureka.png",
      "/images/projects/smartgig-platform/Kafka UI.png",
      "/images/projects/smartgig-platform/User Service.png",
      "/images/projects/smartgig-platform/Project Service.png",
      "/images/projects/smartgig-platform/Gateway Auth.png",
    ],
    featured: true,
  },
  {
    id: 15,
    title: "StreamFlow Analytics",
    description:
      "Production-grade end-to-end data engineering platform — Kafka + Debezium CDC, 4 PySpark Streaming jobs, Delta Lake Medallion architecture, 15+ dbt models, ClickHouse OLAP. 20+ Docker services, one command to run.",
    longDescription:
      "A production-grade, end-to-end data engineering platform simulating the complete data backend of a real e-commerce company — from real-time event streaming to live analytics dashboards. Debezium captures binary log changes from PostgreSQL with zero polling and zero source DB impact. 4 concurrent PySpark 3.5 Structured Streaming jobs run 30-second micro-batches with exactly-once semantics. Delta Lake on MinIO provides ACID transactions, time-travel, and schema evolution on a local S3-compatible lakehouse. 15+ dbt Core models span Silver, Gold, and Mart layers with full lineage, macros, snapshots, and tests. 50+ Great Expectations checks automatically block the DAG when data degrades. Trino enables federated SQL across ClickHouse, PostgreSQL, and MinIO in a single query.",
    highlights: [
      "Debezium CDC binary log capture from PostgreSQL — zero polling, zero source DB impact, BACKWARD Avro schema compatibility enforced at the broker",
      "4 concurrent PySpark 3.5 Structured Streaming jobs with exactly-once semantics and 30s micro-batches on Delta Lake",
      "15+ dbt Core models across Medallion (Bronze/Silver/Gold/Mart) layers with 50+ Great Expectations automated quality checks blocking the DAG on degradation",
      "Sub-second ClickHouse OLAP queries powering live Grafana dashboards + 6 FastAPI REST endpoints served from the Gold layer",
    ],
    principles: [
      "Medallion Architecture",
      "Idempotency",
      "Schema-as-contract",
      "Exactly-once Semantics",
      "CDC (Change Data Capture)",
      "Data Observability",
      "Infrastructure as Code",
    ],
    tech: ["Apache Kafka", "Schema Registry", "Debezium", "PySpark", "Delta Lake", "MinIO", "dbt", "Apache Airflow", "ClickHouse", "Great Expectations", "Trino", "PostgreSQL", "Grafana", "FastAPI", "Docker"],
    github: "https://github.com/albertnanda19/StreamFlow-Analytics",
    deployment: null,
    images: [
      "/images/projects/streamflow-analytics/Complete System Architecture Overview.png",
      "/images/projects/streamflow-analytics/grafana-dashboard.png",
      "/images/projects/streamflow-analytics/airflow-dag.png",
      "/images/projects/streamflow-analytics/kafka-ui-orders-topics.png",
      "/images/projects/streamflow-analytics/clickhouse-playground.png",
      "/images/projects/streamflow-analytics/spark-ui-workers.png",
      "/images/projects/streamflow-analytics/minio-object-browser.png",
    ],
    featured: true,
  },
  {
    id: 16,
    title: "SoundMap",
    description:
      "Production-grade distributed acoustic pollution monitoring system — 5 independent Go microservices communicating exclusively via gRPC, real-time DSP FFT analysis, Uber H3 geospatial indexing, and full OTel observability.",
    longDescription:
      "A production-grade distributed system for real-time acoustic pollution monitoring across urban environments, built entirely with Go and gRPC. SoundMap ingests data from 40 simulated IoT sensors across New York City, runs real-time DSP analysis using a pure Go FFT engine, indexes readings geospatially using Uber's H3 hexagonal grid, fires threshold-based alerts via live push streams, and generates aggregated zone and city-wide reports — all through 5 independent microservices communicating exclusively via gRPC. A single .proto contract drives both REST (via gRPC-Gateway) and gRPC access. Full local stack, zero cloud cost, one command to run everything.",
    highlights: [
      "5 gRPC patterns in one system: Client Streaming (Ingestor), Bidirectional Streaming (Analyzer), Server Streaming (Alert Engine + Geo Index), Unary (Report Service)",
      "Real-time DSP analysis with pure Go FFT engine + Uber H3 hexagonal geospatial indexing for NYC sensor hotspot queries",
      "5-layer interceptor chain: Recovery → JWT Auth → Rate Limiter → Structured Logging → OTel Tracing with W3C trace context across all service boundaries",
      "Full observability: OpenTelemetry, Jaeger distributed tracing, NATS JetStream event streaming, Prometheus + Grafana, graceful 30s drain shutdown",
    ],
    principles: [
      "Proto-first Design",
      "Structured Concurrency (errgroup)",
      "Cache-aside Pattern (Redis)",
      "Interface-based DI",
      "W3C Trace Context Propagation",
      "Graceful Shutdown (30s drain)",
      "Bulk Insert via pgx CopyFrom",
      "Context Propagation on every I/O",
    ],
    tech: ["Go", "gRPC", "Protocol Buffers", "gRPC-Gateway", "TimescaleDB", "Redis", "NATS JetStream", "Uber H3", "OpenTelemetry", "Jaeger", "Prometheus", "Grafana", "Docker", "GitHub Actions"],
    github: "https://github.com/albertnanda19/SoundMap",
    deployment: null,
    images: [
      "/images/projects/sound-map/grafana-dashboard.png",
      "/images/projects/sound-map/Jaeger-UI.png",
      "/images/projects/sound-map/NATS-Connection.png",
      "/images/projects/sound-map/Hotspot Query Result (NYC).png",
      "/images/projects/sound-map/gRPC Live Alert Streaming.png",
      "/images/projects/sound-map/Prometheus - Target Status.png",
    ],
    featured: false,
  },
  {
    id: 17,
    title: "Urban Emotional Intelligence Platform",
    description:
      "End-to-end MLOps system predicting Jakarta's City Mood Score 72 hours ahead — fine-tuned IndoBERT (F1-macro: 0.791), Temporal Fusion Transformer, BERTopic across 450K+ documents, SHAP explainability.",
    longDescription:
      "An end-to-end Data Science system that reads Jakarta's collective emotional state in real-time and predicts it 72 hours into the future — by fusing signals from social media, weather, traffic, news, and city events into a unified City Mood Score (0–100). The system features a fine-tuned IndoBERT model on 7 emotion dimensions achieving F1-macro 0.791 on Indonesian-language tweets, BERTopic topic modeling with multilingual sentence embeddings across 450K+ documents, a Temporal Fusion Transformer with 168-hour lookback and quantile outputs for uncertainty estimation, and a confidence-weighted multi-signal fusion engine handling 5 heterogeneous data streams simultaneously. A Causal Attribution Engine explains mood drivers in natural language via SHAP.",
    highlights: [
      "Fine-tuned IndoBERT on 7 emotion dimensions achieving F1-macro 0.791 on Indonesian-language tweet classification",
      "Temporal Fusion Transformer with 168h lookback, 72h forecast horizon, and quantile outputs for uncertainty estimation",
      "BERTopic topic modeling with multilingual sentence embeddings across 450K+ documents for contextual signal enrichment",
      "Causal Attribution Engine explaining mood drivers via SHAP + Evidently AI automated drift detection + MLflow experiment tracking",
    ],
    principles: [
      "Reproducible ML Pipelines (DVC)",
      "Explainable AI (SHAP)",
      "Automated Drift Detection",
      "Data Quality Validation",
      "Zero-downtime K8s Deployment",
      "Temporal Cross-validation",
      "MLOps Best Practices",
    ],
    tech: ["Python", "IndoBERT", "BERTopic", "Temporal Fusion Transformer", "SHAP", "Evidently AI", "Apache Kafka", "Apache Airflow", "TimescaleDB", "PostgreSQL", "Redis", "MLflow", "DVC", "Great Expectations", "FastAPI", "Streamlit", "Docker", "Kubernetes", "Prometheus", "Grafana"],
    github: "https://github.com/albertnanda19/Urban-Emotional-Intelligence-Platform",
    deployment: null,
    images: [
      "/images/projects/urban-emotional-intelligence-platform/architecture-overview.png",
      "/images/projects/urban-emotional-intelligence-platform/streamlit-dashboard.png",
      "/images/projects/urban-emotional-intelligence-platform/mlflow.png",
      "/images/projects/urban-emotional-intelligence-platform/airflow-dashboard.png",
      "/images/projects/urban-emotional-intelligence-platform/api-docs.png",
      "/images/projects/urban-emotional-intelligence-platform/grafana.png",
    ],
    featured: false,
  },
  {
    id: 1,
    title: "AlForm",
    description:
      "Fast, user-friendly form builder with drag-and-drop editing, submission tracking, and built-in analytics.",
    longDescription:
      "AlForm is a form builder application designed to help individuals and teams collect data efficiently. Users can create forms using a clean drag-and-drop interface, share them with others, review submissions, and monitor statistics — all in a simple, modern UI. Built with Next.js App Router and server components for optimal performance, Clerk for authentication with organization support, and Prisma ORM connected to a PlanetScale serverless MySQL database.",
    highlights: [
      "Drag-and-drop form editor with real-time preview and multiple field types (text, number, select, checkbox, date, etc.)",
      "Submission tracking dashboard with built-in analytics, response rates, and export capabilities",
      "Clerk authentication with organization-level access control for team collaboration",
      "Serverless database architecture using PlanetScale for zero-downtime schema migrations",
    ],
    principles: [
      "Server Components",
      "App Router",
      "Serverless Database",
      "Drag-and-Drop UX",
    ],
    tech: ["Next.js", "Tailwind CSS", "Clerk", "PostgreSQL", "Prisma", "PlanetScale"],
    github: "https://github.com/albertnanda19/AlForm",
    deployment: "https://alform.vercel.app/",
    images: ["/images/projects/project-13.png"],
    featured: false,
  },
  {
    id: 2,
    title: "AlloBoard",
    description:
      "Project management app with organizations and boards to plan, track, and complete work efficiently.",
    longDescription:
      "AlloBoard helps you manage projects in a structured way. You can create organizations to group related projects, then create boards to organize tasks and workflows. Features include drag-and-drop task reordering, board customization, activity logs, and team member management. Built with Next.js, styled using shadcn/ui components and Tailwind CSS, with Clerk handling multi-tenant authentication and PlanetScale as the database backend.",
    highlights: [
      "Organization-based multi-tenancy with role-based access control via Clerk",
      "Kanban-style boards with drag-and-drop task management and real-time reordering",
      "Activity log tracking all board and task changes for full audit trail",
      "Responsive UI built with shadcn/ui component library for consistent design language",
    ],
    principles: [
      "Multi-tenancy",
      "Kanban Workflow",
      "Role-based Access",
      "Component-driven UI",
    ],
    tech: ["Next.js", "Tailwind CSS", "Clerk", "PlanetScale", "Prisma", "shadcn/ui"],
    github: "https://github.com/albertnanda19/AlloBoard",
    deployment: "https://alloboard.vercel.app/",
    images: ["/images/projects/project-12.png"],
    featured: false,
  },
  {
    id: 3,
    title: "AlNote",
    description:
      "Connected workspace for note-taking and planning — capture ideas, manage projects, and stay organized.",
    longDescription:
      "AlNote is a productivity workspace inspired by modern note apps like Notion. It supports rich text editing, organizing content hierarchically, and structuring plans in one place. The app uses Convex as a real-time backend for instant sync across devices, Clerk for authentication, and EdgeStore for file/image uploads. The focus is a clean experience and fast interactions for daily use.",
    highlights: [
      "Rich text editor with block-based content editing and nested page hierarchy",
      "Real-time sync powered by Convex — changes reflect instantly across all connected clients",
      "File and image uploads handled by EdgeStore with automatic optimization",
      "Publish-to-web feature allowing users to share individual notes as public pages",
    ],
    principles: [
      "Real-time Sync",
      "Block-based Editor",
      "Optimistic Updates",
      "File Storage Integration",
    ],
    tech: ["Next.js", "Convex", "Clerk", "EdgeStore", "Tailwind CSS"],
    github: "https://github.com/albertnanda19/AlNote",
    deployment: "https://alnote.vercel.app/",
    images: ["/images/projects/project-11.png"],
    featured: false,
  },
  {
    id: 4,
    title: "AlSnap",
    description:
      "Social media app inspired by Instagram with profiles, posts, comments, and user discovery.",
    longDescription:
      "AlSnap is a social app where users can sign in with Google, follow others, publish posts with captions, customize their profile, receive notifications, search for users, and comment on posts. Built with React and Chakra UI for a polished component-driven interface, backed by Firebase for authentication, real-time database, and cloud storage for media handling.",
    highlights: [
      "Google OAuth authentication with Firebase Auth for seamless sign-in experience",
      "Full social graph: follow/unfollow users, feed algorithm based on followed accounts",
      "Post creation with image uploads to Firebase Cloud Storage and caption editing",
      "Real-time notifications and comment threads powered by Firestore listeners",
    ],
    principles: [
      "OAuth Authentication",
      "Real-time Database",
      "Cloud Storage",
      "Component-driven UI",
    ],
    tech: ["React", "Chakra UI", "Firebase"],
    github: "https://github.com/albertnanda19/AlSnap",
    deployment: "https://alsnap.vercel.app/",
    images: ["/images/projects/project-10.png"],
    featured: false,
  },
  {
    id: 5,
    title: "Unity Chat Application",
    description:
      "Community chat app with sign-up/sign-in, channels, and direct messages powered by GetStream.",
    longDescription:
      "This chat application was built for the Unsrat IT Community (Unity). Users can create an account, sign in, create channels, invite members into channels, and send direct messages to other users. The app integrates GetStream's Chat SDK for real-time messaging infrastructure, with a Node.js backend handling user token generation and authentication flows.",
    highlights: [
      "Real-time messaging via GetStream Chat SDK with typing indicators and read receipts",
      "Channel management: create, join, invite members, and set channel permissions",
      "Direct messaging between users with message history and online presence indicators",
      "Custom Node.js backend for secure token generation and user session management",
    ],
    principles: [
      "Real-time Messaging",
      "Token-based Auth",
      "Channel Architecture",
      "Third-party SDK Integration",
    ],
    tech: ["React", "Tailwind CSS", "GetStream", "Node.js"],
    github: "https://github.com/albertnanda19/Unity-Chat-Application",
    deployment: null,
    images: ["/images/projects/project-9.png"],
    featured: false,
  },
  {
    id: 6,
    title: "Image Search & Free Download",
    description:
      "Web app to search and download free high-quality images from Pexels using their public API.",
    longDescription:
      "This application lets users search for images available on Pexels and download them easily. It uses the Pexels API to fetch and display results based on user queries, with infinite scroll pagination and multiple resolution download options. The UI is built with React and Tailwind CSS for a responsive, grid-based layout optimized for browsing visual content.",
    highlights: [
      "Integration with Pexels API for access to millions of free high-quality stock photos",
      "Infinite scroll pagination for seamless browsing without manual page navigation",
      "Multiple resolution download options (original, large, medium, small) per image",
      "Responsive masonry grid layout adapting to different screen sizes",
    ],
    principles: [
      "API Integration",
      "Infinite Scroll",
      "Responsive Grid",
      "Progressive Loading",
    ],
    tech: ["React", "Tailwind CSS", "Pexels API"],
    github: "https://github.com/albertnanda19/Image-Search-and-Download-using-Pexels-Api",
    deployment: "https://albertm-image-search-and-download-for-free.vercel.app/",
    images: ["/images/projects/project-8.png"],
    featured: false,
  },
  {
    id: 7,
    title: "Translate App",
    description:
      "Translation web app with copy-to-clipboard and text-to-speech features for multi-language support.",
    longDescription:
      "This app translates text between multiple languages using a translation API. It includes quality-of-life features such as copy-to-clipboard for both input and output, text-to-speech to hear pronunciations, language auto-detection, and swap functionality to quickly reverse translation direction. Built with React and styled with Tailwind CSS for a clean, focused interface.",
    highlights: [
      "Multi-language translation powered by external Translation API with auto-detection",
      "Text-to-speech integration using Web Speech API for pronunciation playback",
      "One-click copy-to-clipboard for both source and translated text",
      "Language swap button for instant bidirectional translation reversal",
    ],
    principles: [
      "API Integration",
      "Web Speech API",
      "Clipboard API",
      "Responsive Design",
    ],
    tech: ["React", "Tailwind CSS", "Translation API", "Text-to-Speech"],
    github: "https://github.com/albertnanda19/Translator-using-API",
    deployment: "https://albertm-translate.vercel.app/",
    images: ["/images/projects/project-7.png"],
    featured: false,
  },
  {
    id: 8,
    title: "GitHub Profile Search",
    description:
      "GitHub profile explorer that fetches user details — avatar, stats, repos — using the GitHub API.",
    longDescription:
      "Users can enter a GitHub username to view profile information such as avatar, username, location, bio, follower/following counts, and the number of public repositories. The app fetches data from the GitHub REST API and presents it with clear UI states for loading, error, and empty results. Built with React and styled using Tailwind CSS for a responsive experience.",
    highlights: [
      "GitHub REST API integration for real-time profile data fetching",
      "Display of user stats: followers, following, public repos, join date, and bio",
      "Graceful error handling with distinct UI states for loading, not found, and API rate limits",
      "Clean responsive card layout adapting to mobile and desktop viewports",
    ],
    principles: [
      "REST API Consumption",
      "Error Handling",
      "Loading States",
      "Responsive Layout",
    ],
    tech: ["React", "Tailwind CSS", "GitHub API"],
    github: "https://github.com/albertnanda19/Github-Profile-Search-using-API",
    deployment: "https://albertm-github-profile-search-using-api.vercel.app/",
    images: ["/images/projects/project-6.png"],
    featured: false,
  },
  {
    id: 9,
    title: "Meme Image Generator",
    description:
      "Meme generator where users upload an image, add text overlays, and download the result instantly.",
    longDescription:
      "This web tool allows users to create memes by uploading an image, placing custom top and bottom text overlays with adjustable styling, and exporting the final result as a downloadable image. Built with vanilla HTML, CSS, and JavaScript with Bootstrap for responsive layout. Uses Canvas API for rendering text on images and generating the final composite.",
    highlights: [
      "Image upload with instant preview and Canvas API rendering for text compositing",
      "Customizable top and bottom text with font size, color, and outline controls",
      "One-click download of the finished meme as a PNG file",
      "Bootstrap-based responsive layout working across mobile and desktop browsers",
    ],
    principles: [
      "Canvas API",
      "File Upload Handling",
      "Client-side Rendering",
      "Responsive Bootstrap Grid",
    ],
    tech: ["HTML", "CSS", "JavaScript", "Bootstrap"],
    github: "https://github.com/albertnanda19/Meme-Generator",
    deployment: "https://albertm-meme-generator.vercel.app",
    images: ["/images/projects/project-5.png"],
    featured: false,
  },
  {
    id: 10,
    title: "Gradient Color Generator",
    description:
      "CSS gradient generator that outputs ready-to-copy code for direct use in web projects.",
    longDescription:
      "This tool helps users generate CSS gradients visually by selecting colors, adjusting gradient direction and type (linear/radial), and previewing the result in real-time. It outputs the CSS snippet so the gradient can be copied and used directly in web projects. Built with vanilla HTML, CSS, and JavaScript focusing on a simple, interactive experience.",
    highlights: [
      "Real-time gradient preview updating instantly as users adjust parameters",
      "Support for linear and radial gradient types with direction/angle controls",
      "One-click copy of generated CSS code to clipboard",
      "Color picker integration for intuitive color selection",
    ],
    principles: [
      "Real-time Preview",
      "CSS Generation",
      "Clipboard API",
      "Interactive Controls",
    ],
    tech: ["HTML", "CSS", "JavaScript"],
    github: "https://github.com/albertnanda19/Gradient-Color-Generator",
    deployment: "https://albertm-gradient-color-generator.vercel.app",
    images: ["/images/projects/project-4.png"],
    featured: false,
  },
  {
    id: 11,
    title: "Simple Calculator",
    description:
      "Lightweight calculator web app with basic arithmetic and percentage support in a clean, minimal UI.",
    longDescription:
      "A simple calculator that supports addition, subtraction, multiplication, division, and percentage calculations. Built with vanilla HTML, CSS, and JavaScript as a focused exercise in DOM manipulation, event handling, and state management. Features a clean, minimal UI with responsive behavior and keyboard input support.",
    highlights: [
      "Full arithmetic operations: addition, subtraction, multiplication, division, and percentage",
      "Keyboard input support for fast calculations without mouse interaction",
      "Expression display showing the full calculation chain before evaluation",
      "Responsive layout adapting to different screen sizes with a minimal, focused design",
    ],
    principles: [
      "DOM Manipulation",
      "Event Handling",
      "State Management",
      "Keyboard Accessibility",
    ],
    tech: ["HTML", "CSS", "JavaScript"],
    github: "https://github.com/albertnanda19/Simple-Calculator",
    deployment: "https://albertm-simple-calculator.vercel.app",
    images: ["/images/projects/project-3.png"],
    featured: false,
  },
  {
    id: 12,
    title: "Random Password Generator",
    description:
      "Password generator that creates secure random passwords with one-click copy-to-clipboard.",
    longDescription:
      "This tool generates secure random passwords with configurable length and character sets (uppercase, lowercase, numbers, special characters). Users can adjust the password strength parameters and copy the result with a single click. Built with vanilla HTML, CSS, and JavaScript with a focus on security best practices for client-side password generation using crypto-random values.",
    highlights: [
      "Configurable password length and character set options (uppercase, lowercase, numbers, symbols)",
      "Crypto-random value generation for security-grade password output",
      "One-click copy-to-clipboard with visual confirmation feedback",
      "Password strength indicator showing estimated entropy level",
    ],
    principles: [
      "Cryptographic Randomness",
      "Clipboard API",
      "User Feedback",
      "Security Best Practices",
    ],
    tech: ["HTML", "CSS", "JavaScript"],
    github: "https://github.com/albertnanda19/Random-Password-Generator",
    deployment: "https://albertm-random-password-generator.vercel.app",
    images: ["/images/projects/project-2.png"],
    featured: false,
  },
  {
    id: 13,
    title: "Plotpool — Novel Download Website",
    description:
      "PHP-based website for browsing and downloading novels with a simple, user-friendly download flow.",
    longDescription:
      "Plotpool provides a straightforward experience for downloading novels: users browse the catalog, view novel details, and get redirected to a download page. The project uses classic server-side web fundamentals with PHP handling routing and database queries, MySQL storing the novel catalog and metadata, and a lightweight frontend built with HTML, CSS, and JavaScript for clean navigation.",
    highlights: [
      "Server-side rendered novel catalog with PHP and MySQL backend",
      "Novel detail pages with synopsis, author info, and download links",
      "Search and filter functionality for browsing the novel collection",
      "Simple admin panel for managing the novel database entries",
    ],
    principles: [
      "Server-side Rendering",
      "CRUD Operations",
      "MySQL Queries",
      "MVC-lite Architecture",
    ],
    tech: ["HTML", "CSS", "JavaScript", "PHP", "MySQL"],
    github: "https://github.com/albertnanda19/plotpool-web",
    deployment: "https://plotpool69.000webhostapp.com/index.html",
    images: ["/images/projects/project-1.png"],
    featured: false,
  },
];

export const experiences = [
  {
    id: 0,
    role: "Frontend Engineer",
    company: "Dibimbing.ID — Cakrawala University",
    type: "Full-time",
    period: "Jan 2026 – Present",
    description:
      "Serving as Frontend Engineer at Dibimbing.ID, an education technology company building Cakrawala University from the ground up. Responsible for architecting and developing the entire frontend ecosystem of four core university systems: SIAKAD (Academic Information System), SPMB (Student Admission System), Edlink (Learning Management System), and the Cakrawala University Landing Page. Despite the frontend role title, actively contributing to the backend development using Go Fiber with PostgreSQL, Redis, and Kafka for event-driven communication between services. Leading frontend technical decisions including component library standardization, design system implementation, and cross-application state management patterns. Building responsive, accessible interfaces with Next.js, Chakra UI, Tailwind CSS, shadcn/ui, and Astro for the static landing page powered by Strapi CMS.",
    tech: ["Next.js", "Chakra UI", "Tailwind CSS", "shadcn/ui", "Astro", "Strapi", "Go Fiber", "PostgreSQL", "Redis", "Apache Kafka", "TypeScript", "REST API"],
    current: true,
  },
  {
    id: 1,
    role: "Frontend Developer",
    company: "JA Software Solutions LIMITED",
    type: "Full-time",
    period: "Apr 2025 – Dec 2026",
    description:
      "Built high-performance, data-intensive interfaces for Nova — a Web3 trading and analytics platform serving real-time market data. Engineered UI components capable of handling high-frequency data updates with sub-100ms render cycles, ensuring smooth interactions under heavy WebSocket traffic. Collaborated with backend and blockchain teams to integrate wallet connections, transaction history visualization, and live order book rendering. Implemented advanced performance optimization techniques including virtualized lists, memoization strategies, and Web Worker offloading for CPU-intensive data transformations. Delivered pixel-perfect responsive layouts across desktop and mobile viewports while maintaining consistent UX under varying network conditions.",
    tech: ["React", "TypeScript", "Tailwind CSS", "Web3", "WebSocket", "REST API"],
    current: false,
  },
  {
    id: 2,
    role: "Tech Lead",
    company: "UNITY – UKM Mahasiswa IT UNSRAT",
    type: "Organization",
    period: "Aug 2024 – Nov 2024",
    description:
      "Led the technical division of the university's premier IT student organization, overseeing four concurrent development projects with dedicated Dev Lead for each team. Defined technical roadmaps, established coding standards, conducted architecture reviews, and resolved cross-team blockers to ensure all projects shipped on schedule. The four projects under my leadership: (1) Report Formatter — automated thesis formatting tool that generates KTIS-compliant academic papers using LaTeX templating; (2) Techoverse — a metaverse game simulating Universitas Sam Ratulangi's campus environment; (3) Spark — an LLM development project fine-tuning Meta's Llama pre-trained model for domain-specific use cases; (4) Crypnity — a cryptocurrency coin (Unybit) built on the Solana blockchain. Managed sprint planning, technical mentoring, and stakeholder presentations across all teams.",
    tech: ["React", "Next.js", "TypeScript", "Node.js", "PostgreSQL", "LaTeX", "Solana", "Python"],
    current: false,
  },
  {
    id: 3,
    role: "Dev Lead — Crypnity",
    company: "UNITY – UKM Mahasiswa IT UNSRAT",
    type: "Organization",
    period: "Aug 2024 – Nov 2024",
    description:
      "Concurrently served as Development Lead for Crypnity, one of the four projects under the UNITY Tech Lead umbrella. Led a team of developers to build Unybit — a cryptocurrency token deployed on the Solana blockchain network. Directed the full development lifecycle from smart contract design to frontend dashboard implementation. Managed technical architecture decisions, coordinated with the broader Tech Lead structure for resource allocation, and presented project milestones to faculty advisors and organization stakeholders. Delivered a functional token with wallet integration, transaction tracking, and a landing page showcasing the project's vision.",
    tech: ["React", "TypeScript", "Solana", "Node.js", "Tailwind CSS"],
    current: false,
  },
  {
    id: 4,
    role: "Senior Frontend Developer",
    company: "PT. UNITY Membangun Bangsa",
    type: "Full-time",
    period: "Feb 2024 – Jul 2026",
    description:
      "Led frontend architecture decisions and enforced code quality standards on Renify — a professional SaaS product serving enterprise clients. Established component design patterns, implemented comprehensive code review workflows, and mentored three junior developers through pair programming sessions and technical knowledge sharing. Drove the migration from legacy patterns to modern React best practices including server components, optimistic UI updates, and advanced caching strategies. Collaborated closely with backend engineers and product managers in agile sprints to deliver production-grade features with high test coverage. Reduced page load times by 40% through bundle optimization, lazy loading, and image optimization strategies.",
    tech: ["React", "Next.js", "TypeScript", "Tailwind CSS", "REST API", "Redux", "Jest"],
    current: false,
  },
  {
    id: 5,
    role: "Backend Developer Intern",
    company: "Bank BTN – Manado Branch",
    type: "Internship",
    period: "Jan 2024 – Mar 2024",
    description:
      "Contributed to BTN Boost — an internal KPI monitoring and performance tracking system used by the Manado branch for operational analysis. Implemented core business logic for KPI calculations, employee performance scoring algorithms, and automated report generation pipelines. Built RESTful API endpoints handling complex data aggregation queries across multiple database tables. Gained hands-on experience in enterprise software development practices including version control workflows, code reviews, and documentation standards. Collaborated with branch managers to translate business requirements into technical specifications and delivered features within tight sprint deadlines.",
    tech: ["Node.js", "Express.js", "MySQL", "REST API"],
    current: false,
  },
  {
    id: 6,
    role: "Frontend Developer",
    company: "UNITY – UKM Mahasiswa IT UNSRAT",
    type: "Organization",
    period: "Jul 2023 – Nov 2023",
    description:
      "Contributed as frontend developer in the university IT student organization's annual project cycle, working on Report Formatter — a web-based academic report formatting application. Built structured UI components for document editing, template selection, and real-time preview rendering. Implemented the KTIS (Karya Tulis Ilmiah Sarjana) formatting rules as configurable templates, enabling students to generate properly formatted thesis documents automatically. Collaborated with the team's backend developers on API integration and participated in weekly sprint reviews. This experience laid the foundation for my technical leadership role in the following year.",
    tech: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS", "LaTeX"],
    current: false,
  },
];

export const certificates = [
  {
    id: 1,
    title: "Frontend Development Lead",
    issuer: "UNITY – UKM Mahasiswa IT UNSRAT",
    date: "2024",
    credentialId: "",
    image: "/images/certificate/cert-frontend-lead.webp",
    link: "#",
  },
  {
    id: 2,
    title: "Tech Lead",
    issuer: "UNITY – UKM Mahasiswa IT UNSRAT",
    date: "2024",
    credentialId: "",
    image: "/images/certificate/cert-tech-lead.webp",
    link: "#",
  },
  {
    id: 3,
    title: "Development Lead – Crypnity",
    issuer: "UNITY – UKM Mahasiswa IT UNSRAT",
    date: "2024",
    credentialId: "",
    image: "/images/certificate/cert-dev-lead-crypnity.webp",
    link: "#",
  },
];

export const contact = {
  email: "alberttmangiri@gmail.com",
  github: "https://github.com/albertnanda19",
  linkedin: "https://linkedin.com/in/albertmangiri",
  instagram: "https://instagram.com/albert.fnc",
  website: "https://albertm.vercel.app/",
};
