export const roles = [
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Data Engineer",
  "Data Analyst",
  "DevOps Engineer",
  "Full-Stack Developer",
  "IT Enthusiast",
  "Tech Lead",
];

export const techStack = {
  frontend: [
    { name: "React", icon: "⚛️" },
    { name: "Next.js", icon: "▲" },
    { name: "Vue.js", icon: "💚" },
    { name: "TypeScript", icon: "🔷" },
    { name: "JavaScript", icon: "🟨" },
    { name: "Tailwind CSS", icon: "🎨" },
    { name: "SCSS/SASS", icon: "🎭" },
    { name: "Redux", icon: "🔄" },
    { name: "Zustand", icon: "🐻" },
    { name: "React Query", icon: "🔃" },
    { name: "Framer Motion", icon: "🎬" },
    { name: "HTML5", icon: "🌐" },
  ],
  backend: [
    { name: "Node.js", icon: "🟢" },
    { name: "Express.js", icon: "🚂" },
    { name: "NestJS", icon: "🐈" },
    { name: "Python", icon: "🐍" },
    { name: "FastAPI", icon: "⚡" },
    { name: "Django", icon: "🎸" },
    { name: "Go", icon: "🔵" },
    { name: "REST API", icon: "🔌" },
    { name: "GraphQL", icon: "⬡" },
    { name: "WebSocket", icon: "📡" },
    { name: "gRPC", icon: "🔗" },
    { name: "Laravel", icon: "🔴" },
  ],
  database: [
    { name: "PostgreSQL", icon: "🐘" },
    { name: "MySQL", icon: "🐬" },
    { name: "MongoDB", icon: "🍃" },
    { name: "Redis", icon: "🔴" },
    { name: "Elasticsearch", icon: "🔍" },
    { name: "Supabase", icon: "⚡" },
    { name: "Firebase", icon: "🔥" },
    { name: "SQLite", icon: "📦" },
    { name: "DynamoDB", icon: "🟠" },
    { name: "ClickHouse", icon: "🏠" },
  ],
  devops: [
    { name: "Docker", icon: "🐳" },
    { name: "Kubernetes", icon: "☸️" },
    { name: "CI/CD", icon: "🔄" },
    { name: "GitHub Actions", icon: "⚙️" },
    { name: "Jenkins", icon: "🎩" },
    { name: "AWS", icon: "☁️" },
    { name: "GCP", icon: "🌤️" },
    { name: "Nginx", icon: "⚡" },
    { name: "Linux", icon: "🐧" },
    { name: "Terraform", icon: "🏗️" },
  ],
  data: [
    { name: "Apache Spark", icon: "✨" },
    { name: "Apache Kafka", icon: "📨" },
    { name: "Airflow", icon: "🌊" },
    { name: "dbt", icon: "🔧" },
    { name: "Pandas", icon: "🐼" },
    { name: "NumPy", icon: "🔢" },
    { name: "Power BI", icon: "📊" },
    { name: "Tableau", icon: "📈" },
    { name: "Jupyter", icon: "📓" },
    { name: "Looker", icon: "👁️" },
  ],
  tools: [
    { name: "VS Code", icon: "💙" },
    { name: "Postman", icon: "📮" },
    { name: "Figma", icon: "🎨" },
    { name: "APIDog", icon: "🐕" },
    { name: "DBeaver", icon: "🦦" },
    { name: "Git", icon: "📝" },
    { name: "GitHub", icon: "🐙" },
    { name: "Jira", icon: "📋" },
    { name: "Notion", icon: "📄" },
    { name: "Slack", icon: "💬" },
    { name: "Insomnia", icon: "😴" },
    { name: "TablePlus", icon: "🔷" },
  ],
  monitoring: [
    { name: "Grafana", icon: "📊" },
    { name: "Prometheus", icon: "🔥" },
    { name: "Datadog", icon: "🐶" },
    { name: "Sentry", icon: "🛡️" },
    { name: "New Relic", icon: "🟣" },
    { name: "ELK Stack", icon: "🦌" },
    { name: "Jaeger", icon: "🔍" },
    { name: "OpenTelemetry", icon: "📡" },
  ],
};

export const projects = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description:
      "Full-stack e-commerce platform with real-time inventory, payment integration, and analytics dashboard. Built for scale with microservices architecture.",
    tech: ["Next.js", "Node.js", "PostgreSQL", "Redis", "Docker", "Stripe"],
    github: "https://github.com/albertmangiri",
    deployment: null,
    images: ["/images/projects/placeholder-1.jpg"],
    featured: true,
  },
  {
    id: 2,
    title: "Real-Time Analytics Dashboard",
    description:
      "Data pipeline ingesting millions of events per day with real-time visualization. Custom ETL pipeline with Apache Kafka and ClickHouse.",
    tech: ["Apache Kafka", "ClickHouse", "React", "Python", "FastAPI", "Grafana"],
    github: "https://github.com/albertmangiri",
    deployment: null,
    images: ["/images/projects/placeholder-2.jpg"],
    featured: true,
  },
  {
    id: 3,
    title: "DevOps Automation Platform",
    description:
      "Internal platform for CI/CD pipeline management, infrastructure provisioning, and deployment monitoring across multiple cloud providers.",
    tech: ["Go", "Kubernetes", "Terraform", "AWS", "React", "PostgreSQL"],
    github: "https://github.com/albertmangiri",
    deployment: null,
    images: ["/images/projects/placeholder-3.jpg"],
    featured: false,
  },
  {
    id: 4,
    title: "Smart Inventory Management",
    description:
      "IoT-integrated inventory system with ML-powered demand forecasting and automated reorder points. Mobile-first PWA with offline support.",
    tech: ["React Native", "Python", "TensorFlow", "Firebase", "FastAPI"],
    github: "https://github.com/albertmangiri",
    deployment: null,
    images: ["/images/projects/placeholder-4.jpg"],
    featured: false,
  },
  {
    id: 5,
    title: "Collaborative Workspace",
    description:
      "Real-time collaborative workspace with live document editing, video conferencing integration, and project management features.",
    tech: ["Next.js", "WebSocket", "WebRTC", "MongoDB", "Redis", "NestJS"],
    github: "https://github.com/albertmangiri",
    deployment: null,
    images: ["/images/projects/placeholder-5.jpg"],
    featured: false,
  },
  {
    id: 6,
    title: "Data Lake Infrastructure",
    description:
      "Enterprise data lake setup with automated ingestion pipelines, data quality checks, and self-service analytics portal for non-technical teams.",
    tech: ["Apache Spark", "Airflow", "dbt", "Snowflake", "Python", "Tableau"],
    github: "https://github.com/albertmangiri",
    deployment: null,
    images: ["/images/projects/placeholder-6.jpg"],
    featured: false,
  },
];

export const experiences = [
  {
    id: 1,
    role: "Tech Lead",
    company: "Company Name",
    type: "Full-time",
    period: "2024 – Present",
    description:
      "Leading engineering team of 8, architecting scalable systems, defining technical roadmap, and driving DevOps culture. Responsible for system design reviews and cross-team technical alignment.",
    tech: ["Next.js", "Node.js", "AWS", "Kubernetes", "PostgreSQL"],
    current: true,
  },
  {
    id: 2,
    role: "Senior Full-Stack Developer",
    company: "Company Name",
    type: "Full-time",
    period: "2022 – 2024",
    description:
      "Built and maintained core product features. Led migration from monolith to microservices. Mentored junior developers and established code review processes.",
    tech: ["React", "NestJS", "Docker", "Redis", "TypeScript"],
    current: false,
  },
  {
    id: 3,
    role: "Data Engineer",
    company: "Company Name",
    type: "Full-time",
    period: "2021 – 2022",
    description:
      "Designed and implemented data pipelines processing 50M+ events daily. Built data warehouse architecture and self-service BI tooling.",
    tech: ["Apache Spark", "Airflow", "Python", "ClickHouse", "dbt"],
    current: false,
  },
  {
    id: 4,
    role: "Software Engineer Intern",
    company: "Company Name",
    type: "Internship",
    period: "2020 – 2021",
    description:
      "Developed REST APIs and frontend features. Gained hands-on experience with production systems and agile development practices.",
    tech: ["Vue.js", "Laravel", "MySQL", "Docker"],
    current: false,
  },
  {
    id: 5,
    role: "Head of Technology",
    company: "UKM IT Campus",
    type: "Organization",
    period: "2019 – 2020",
    description:
      "Led the IT student organization's technical division. Organized workshops, built campus tech projects, and recruited & mentored fellow students into software development.",
    tech: ["JavaScript", "PHP", "MySQL", "WordPress"],
    current: false,
  },
  {
    id: 6,
    role: "Member",
    company: "UKM IT Campus",
    type: "Organization",
    period: "2018 – 2019",
    description:
      "Joined the IT student organization. Participated in hackathons, learned web development fundamentals, and collaborated on campus digital projects.",
    tech: ["HTML", "CSS", "JavaScript", "PHP"],
    current: false,
  },
];

export const certificates = [
  {
    id: 1,
    title: "AWS Certified Solutions Architect",
    issuer: "Amazon Web Services",
    date: "2023",
    credentialId: "AWS-SAA-XXXXX",
    image: "/images/certs/cert-1.jpg",
    link: "#",
  },
  {
    id: 2,
    title: "Professional Data Engineer",
    issuer: "Google Cloud",
    date: "2023",
    credentialId: "GCP-PDE-XXXXX",
    image: "/images/certs/cert-2.jpg",
    link: "#",
  },
  {
    id: 3,
    title: "Certified Kubernetes Administrator",
    issuer: "Cloud Native Computing Foundation",
    date: "2022",
    credentialId: "CKA-XXXXX",
    image: "/images/certs/cert-3.jpg",
    link: "#",
  },
];

export const contact = {
  email: "alberttmangiri@gmail.com",
  github: "https://github.com/albertmangiri",
  linkedin: "https://linkedin.com/in/albertmangiri",
  instagram: "https://instagram.com/albertmangiri",
  website: "https://albertmangiri.dev",
};
