import {
  SiReact, SiNextdotjs, SiVuedotjs, SiTypescript, SiJavascript,
  SiTailwindcss, SiSass, SiRedux, SiFramer, SiHtml5,
  SiBootstrap, SiChakraui, SiShadcnui, SiMui, SiReactquery,
  SiNodedotjs, SiExpress, SiNestjs, SiPython, SiFastapi,
  SiDjango, SiGo, SiGraphql, SiLaravel, SiSpringboot,
  SiClerk, SiPrisma, SiFastify, SiCodeigniter,
  SiPostgresql, SiMysql, SiMongodb, SiRedis, SiElasticsearch,
  SiSupabase, SiFirebase, SiSqlite, SiClickhouse, SiPlanetscale,
  SiDocker, SiKubernetes, SiGithubactions, SiJenkins,
  SiGooglecloud, SiNginx, SiLinux, SiTerraform,
  SiApachespark, SiApachekafka, SiApacheairflow, SiDbt,
  SiPandas, SiNumpy, SiJupyter, SiStreamlit, SiMlflow, SiDvc, SiTrino, SiMinio,
  SiGit, SiGithub, SiJira, SiNotion, SiSlack, SiPostman, SiFigma, SiInsomnia,
  SiGrafana, SiPrometheus, SiDatadog, SiSentry, SiOpentelemetry, SiJaeger, SiNewrelic,
  SiFlask, SiFlutter, SiElectron,
  SiCypress, SiJest, SiStorybook,
  SiJsonwebtokens, SiAuth0,
  SiAstro,
  SiOpencv, SiTensorflow, SiScikitlearn, SiR,
  SiPhp,
  SiCss,
  SiApache,
  SiDbeaver,
} from "react-icons/si";
import { IconType } from "react-icons";
import { Cloud, Monitor, BarChart3, LayoutGrid, Sword } from "lucide-react";

export const techIconMap: Record<string, IconType | React.ComponentType<{ size?: number; color?: string; style?: React.CSSProperties }>> = {
  "React": SiReact,
  "Next.js": SiNextdotjs,
  "Vue.js": SiVuedotjs,
  "TypeScript": SiTypescript,
  "JavaScript": SiJavascript,
  "Tailwind CSS": SiTailwindcss,
  "SCSS/SASS": SiSass,
  "Redux": SiRedux,
  "Framer Motion": SiFramer,
  "HTML5": SiHtml5,
  "HTML": SiHtml5,
  "CSS": SiCss,
  "CSS3": SiCss,
  "Bootstrap": SiBootstrap,
  "Chakra UI": SiChakraui,
  "shadcn/ui": SiShadcnui,
  "ShadCN": SiShadcnui,
  "Material UI": SiMui,
  "React Query": SiReactquery,
  "Astro": SiAstro,
  "Electron": SiElectron,
  "Flutter": SiFlutter,

  "Jest": SiJest,
  "Cypress": SiCypress,
  "Playwright": Sword,
  "Storybook": SiStorybook,

  "Java": SiApache,
  "Node.js": SiNodedotjs,
  "Express.js": SiExpress,
  "NestJS": SiNestjs,
  "Python": SiPython,
  "FastAPI": SiFastapi,
  "Django": SiDjango,
  "Flask": SiFlask,
  "Go": SiGo,
  "GraphQL": SiGraphql,
  "Laravel": SiLaravel,
  "Spring Boot": SiSpringboot,
  "Clerk": SiClerk,
  "Prisma": SiPrisma,
  "Fastify": SiFastify,
  "CodeIgniter 4": SiCodeigniter,
  "PHP": SiPhp,
  "R": SiR,

  "JWT": SiJsonwebtokens,
  "OAuth": SiAuth0,

  "PostgreSQL": SiPostgresql,
  "MySQL": SiMysql,
  "MongoDB": SiMongodb,
  "Redis": SiRedis,
  "Elasticsearch": SiElasticsearch,
  "Supabase": SiSupabase,
  "Firebase": SiFirebase,
  "SQLite": SiSqlite,
  "ClickHouse": SiClickhouse,
  "PlanetScale": SiPlanetscale,
  "Convex": LayoutGrid,

  "Docker": SiDocker,
  "Kubernetes": SiKubernetes,
  "GitHub Actions": SiGithubactions,
  "Jenkins": SiJenkins,
  "AWS": Cloud,
  "GCP": SiGooglecloud,
  "Nginx": SiNginx,
  "Linux": SiLinux,
  "Terraform": SiTerraform,

  "Apache Spark": SiApachespark,
  "PySpark": SiApachespark,
  "Apache Kafka": SiApachekafka,
  "Airflow": SiApacheairflow,
  "Apache Airflow": SiApacheairflow,
  "dbt": SiDbt,
  "Pandas": SiPandas,
  "NumPy": SiNumpy,
  "Jupyter": SiJupyter,
  "Streamlit": SiStreamlit,
  "MLflow": SiMlflow,
  "DVC": SiDvc,
  "Trino": SiTrino,
  "MinIO": SiMinio,
  "Power BI": BarChart3,
  "Tableau": BarChart3,
  "TensorFlow": SiTensorflow,
  "Scikit-learn": SiScikitlearn,
  "OpenCV": SiOpencv,

  "Git": SiGit,
  "GitHub": SiGithub,
  "Jira": SiJira,
  "Notion": SiNotion,
  "Slack": SiSlack,
  "Postman": SiPostman,
  "Figma": SiFigma,
  "Insomnia": SiInsomnia,
  "VS Code": Monitor,
  "DBeaver": SiDbeaver,
  "XAMPP": SiApache,

  "Grafana": SiGrafana,
  "Prometheus": SiPrometheus,
  "Datadog": SiDatadog,
  "Sentry": SiSentry,
  "OpenTelemetry": SiOpentelemetry,
  "Jaeger": SiJaeger,
  "New Relic": SiNewrelic,
};

export const techColorMap: Record<string, string> = {
  "React": "#61DAFB",
  "Next.js": "#ffffff",
  "Vue.js": "#4FC08D",
  "TypeScript": "#3178C6",
  "JavaScript": "#F7DF1E",
  "Tailwind CSS": "#06B6D4",
  "SCSS/SASS": "#CC6699",
  "Redux": "#764ABC",
  "Framer Motion": "#FF0055",
  "HTML5": "#E34F26",
  "HTML": "#E34F26",
  "CSS": "#1572B6",
  "CSS3": "#1572B6",
  "Bootstrap": "#7952B3",
  "Chakra UI": "#319795",
  "shadcn/ui": "#e2e8f0",
  "ShadCN": "#e2e8f0",
  "Material UI": "#007FFF",
  "React Query": "#FF4154",
  "Zustand": "#f97316",
  "Astro": "#FF5D01",
  "Electron": "#47848F",
  "Flutter": "#02569B",

  "Jest": "#C21325",
  "Cypress": "#69D3A7",
  "Playwright": "#2EAD33",
  "Storybook": "#FF4785",

  "Node.js": "#339933",
  "Express.js": "#e2e8f0",
  "NestJS": "#E0234E",
  "Python": "#3776AB",
  "FastAPI": "#009688",
  "Django": "#44B78B",
  "Flask": "#e2e8f0",
  "Go": "#00ADD8",
  "GraphQL": "#E10098",
  "Laravel": "#FF2D20",
  "Spring Boot": "#6DB33F",
  "Java": "#ED8B00",
  "REST API": "#58a6ff",
  "WebSocket": "#a371f7",
  "gRPC": "#6aaa64",
  "Protocol Buffers": "#a371f7",
  "JWT": "#FB015B",
  "OAuth": "#EB5424",
  "Clerk": "#6C47FF",
  "Prisma": "#5a67d8",
  "Fastify": "#e2e8f0",
  "CodeIgniter 4": "#EF4223",
  "NATS JetStream": "#27AAE1",
  "PHP": "#777BB4",
  "R": "#276DC3",

  "PostgreSQL": "#4169E1",
  "MySQL": "#4479A1",
  "MongoDB": "#47A248",
  "Redis": "#DC382D",
  "Elasticsearch": "#00BFB3",
  "Supabase": "#3ECF8E",
  "Firebase": "#FFCA28",
  "SQLite": "#003B57",
  "DynamoDB": "#FF9900",
  "ClickHouse": "#FFCC00",
  "TimescaleDB": "#FDB515",
  "PlanetScale": "#a371f7",
  "Convex": "#F9826C",

  "Docker": "#2496ED",
  "Kubernetes": "#326CE5",
  "AWS": "#FF9900",
  "GCP": "#4285F4",
  "Nginx": "#009639",
  "Linux": "#FCC624",
  "Terraform": "#7B42BC",
  "Jenkins": "#D24939",
  "CI/CD": "#58a6ff",
  "GitHub Actions": "#2088FF",

  "Apache Spark": "#E25A1C",
  "PySpark": "#E25A1C",
  "Apache Kafka": "#7c8cf8",
  "Airflow": "#017CEE",
  "Apache Airflow": "#017CEE",
  "dbt": "#FF694B",
  "Pandas": "#5C0091",
  "NumPy": "#4DABCF",
  "Jupyter": "#F37626",
  "Power BI": "#F2C811",
  "Tableau": "#E97627",
  "Streamlit": "#FF4B4B",
  "MLflow": "#0194E2",
  "DVC": "#945DD6",
  "Trino": "#DD00A1",
  "MinIO": "#C72E49",
  "Delta Lake": "#00ADD8",
  "Debezium": "#E0234E",
  "Great Expectations": "#2ECC71",
  "TensorFlow": "#FF6F00",
  "Scikit-learn": "#F7931E",
  "OpenCV": "#5C3EE8",

  "VS Code": "#007ACC",
  "Postman": "#FF6C37",
  "Figma": "#F24E1E",
  "Git": "#F05032",
  "GitHub": "#e2e8f0",
  "Jira": "#0052CC",
  "Notion": "#e2e8f0",
  "Slack": "#4A154B",
  "DBeaver": "#58a6ff",
  "APIDog": "#a371f7",
  "TablePlus": "#3fb950",
  "Insomnia": "#4000BF",
  "XAMPP": "#FB7A24",
  "EdgeStore": "#58a6ff",
  "GetStream": "#005FFF",

  "Grafana": "#F46800",
  "Prometheus": "#E6522C",
  "Datadog": "#632CA6",
  "Sentry": "#362D59",
  "ELK Stack": "#00BFB3",
  "New Relic": "#00AC69",
  "Jaeger": "#60D0E4",
  "OpenTelemetry": "#f5a800",
  "Zipkin": "#FE8A00",
};
