import {
  SiReact, SiNextdotjs, SiVuedotjs, SiTypescript, SiJavascript,
  SiTailwindcss, SiSass, SiRedux, SiFramer, SiHtml5,
  SiNodedotjs, SiExpress, SiNestjs, SiPython, SiFastapi,
  SiDjango, SiGo, SiGraphql, SiLaravel,
  SiPostgresql, SiMysql, SiMongodb, SiRedis, SiElasticsearch,
  SiSupabase, SiFirebase, SiSqlite,
  SiDocker, SiKubernetes, SiGithubactions, SiJenkins,
  SiGooglecloud, SiNginx, SiLinux, SiTerraform,
  SiApachespark, SiApachekafka, SiPandas, SiNumpy, SiJupyter,
  SiGit, SiGithub, SiJira, SiNotion, SiSlack, SiPostman, SiFigma,
  SiGrafana, SiPrometheus, SiDatadog, SiSentry,
} from "react-icons/si";
import { IconType } from "react-icons";
import { Cloud } from "lucide-react";

// Map tech name → SI icon component
export const techIconMap: Record<string, IconType | React.ComponentType<{ size?: number; color?: string; style?: React.CSSProperties }>> = {
  "React": SiReact,
  "Next.js": SiNextdotjs,
  "Vue.js": SiVuedotjs,
  "TypeScript": SiTypescript,
  "JavaScript": SiJavascript,
  "Tailwind CSS": SiTailwindcss,
  "SCSS/SASS": SiSass,
  "Redux": SiRedux,
  "Framer Motion": SiFramer,
  "HTML5": SiHtml5,

  "Node.js": SiNodedotjs,
  "Express.js": SiExpress,
  "NestJS": SiNestjs,
  "Python": SiPython,
  "FastAPI": SiFastapi,
  "Django": SiDjango,
  "Go": SiGo,
  "GraphQL": SiGraphql,
  "Laravel": SiLaravel,

  "PostgreSQL": SiPostgresql,
  "MySQL": SiMysql,
  "MongoDB": SiMongodb,
  "Redis": SiRedis,
  "Elasticsearch": SiElasticsearch,
  "Supabase": SiSupabase,
  "Firebase": SiFirebase,
  "SQLite": SiSqlite,

  "Docker": SiDocker,
  "Kubernetes": SiKubernetes,
  "GitHub Actions": SiGithubactions,
  "Jenkins": SiJenkins,
  "AWS": Cloud, // fallback
  "GCP": SiGooglecloud,
  "Nginx": SiNginx,
  "Linux": SiLinux,
  "Terraform": SiTerraform,

  "Apache Spark": SiApachespark,
  "Apache Kafka": SiApachekafka,
  "Pandas": SiPandas,
  "NumPy": SiNumpy,
  "Jupyter": SiJupyter,

  "Git": SiGit,
  "GitHub": SiGithub,
  "Jira": SiJira,
  "Notion": SiNotion,
  "Slack": SiSlack,
  "Postman": SiPostman,
  "Figma": SiFigma,

  "Grafana": SiGrafana,
  "Prometheus": SiPrometheus,
  "Datadog": SiDatadog,
  "Sentry": SiSentry,
};

// SI brand colors
export const techColorMap: Record<string, string> = {
  "React": "#61DAFB",
  "Next.js": "#ffffff",
  "Vue.js": "#4FC08D",
  "TypeScript": "#3178C6",
  "JavaScript": "#F7DF1E",
  "Tailwind CSS": "#06B6D4",
  "SCSS/SASS": "#CC6699",
  "Redux": "#764ABC",
  "Framer Motion": "#FF0055",
  "HTML5": "#E34F26",

  "Node.js": "#339933",
  "Express.js": "#ffffff",
  "NestJS": "#E0234E",
  "Python": "#3776AB",
  "FastAPI": "#009688",
  "Django": "#092E20",
  "Go": "#00ADD8",
  "GraphQL": "#E10098",
  "Laravel": "#FF2D20",
  "REST API": "#58a6ff",
  "WebSocket": "#a371f7",
  "gRPC": "#6aaa64",

  "PostgreSQL": "#4169E1",
  "MySQL": "#4479A1",
  "MongoDB": "#47A248",
  "Redis": "#DC382D",
  "Elasticsearch": "#005571",
  "Supabase": "#3ECF8E",
  "Firebase": "#FFCA28",
  "SQLite": "#003B57",
  "DynamoDB": "#FF9900",
  "ClickHouse": "#FFCC00",

  "Docker": "#2496ED",
  "Kubernetes": "#326CE5",
  "AWS": "#FF9900",
  "GCP": "#4285F4",
  "Nginx": "#009639",
  "Linux": "#FCC624",
  "Terraform": "#7B42BC",
  "Jenkins": "#D24939",
  "CI/CD": "#58a6ff",
  "GitHub Actions": "#2088FF",

  "Apache Spark": "#E25A1C",
  "Apache Kafka": "#231F20",
  "Airflow": "#017CEE",
  "dbt": "#FF694B",
  "Pandas": "#150458",
  "NumPy": "#013243",
  "Jupyter": "#F37626",
  "Power BI": "#F2C811",
  "Tableau": "#E97627",
  "Looker": "#4285F4",

  "VS Code": "#007ACC",
  "Postman": "#FF6C37",
  "Figma": "#F24E1E",
  "Git": "#F05032",
  "GitHub": "#ffffff",
  "Jira": "#0052CC",
  "Notion": "#ffffff",
  "Slack": "#4A154B",
  "DBeaver": "#58a6ff",
  "APIDog": "#a371f7",
  "TablePlus": "#3fb950",
  "Insomnia": "#4000BF",

  "Grafana": "#F46800",
  "Prometheus": "#E6522C",
  "Datadog": "#632CA6",
  "Sentry": "#362D59",
  "ELK Stack": "#005571",
  "New Relic": "#00AC69",
  "Jaeger": "#60D0E4",
  "OpenTelemetry": "#f5a800",
};
